{% set name = "backward-cpp" %}
{% set version = "1.3" %}
{% set sha256 = "4bf3fb7029ff551acda6578d9d8e13d438ebdd82a787a82b157728e3af6b5dec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/bombela/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - cmake
    - toolchain
    - elfutils  # so that the tests compiled in the build step can link to libdw

test:
  requires:
    - cmake
    - toolchain
    - elfutils

about:
  home: https://github.com/bombela/backward-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Backward is a beautiful stack trace pretty printer for C++.'
  doc_url: https://github.com/bombela/backward-cpp/blob/master/README.md
  dev_url: https://github.com/bombela/backward-cpp

extra:
  recipe-maintainers:
    - edisongustavo
    - bombela
