travis:
  secure:
    BINSTAR_TOKEN: 3NpPlFd2sofThcHgWRMEAVMApmMFqNIX4oMyXfpWMAZJpB0SY+7EFnfolD163+IzjZ829fEQ5/QzqB02De1pf7h2OYiGmBfwiYfDqFW1/6acRvid5hoNTaiVugYD+Cs64FUe6i0gwk7q3YhX2nlcfx+Jfeu1chyrKxfEvxs2vOQ1cFullrtAo2uSG849pxgu2ZuzyX8v+cxLA7xXHhglAHoQuaIDbdzR3EeiU0I9R7+XbFu10C5sDeEwM+nRQWw8ymGxfBjnCKZ1aX+VHvpy+BIvpeYebL9RHrl8U5xfKT/icGXixQVRbXmxSRxFDvDe4+j9ZC0ID+1ly7a4LT4lM18ZNM5KxJe6mAarD2lS2QevwInC7bMz5CuN8H8yRFBEt385StVEmP1kvnec3GtrYqOvyvnSoXgBiz+d6Md3s/belV9EPcP7AlYPXhTcEI368nBpd13Aa1CuiFHWc5kzLuQnVIFjie5zoTIAWL0LejSKG90UUyrgmouSMTCwKagdjxZcgj34XcZQoqom+QhPZ4wqfoSQhb1FFKx/m1+yS4GJRc8JRMs9b3G1nGSwAXXZX8wXPD/QPuE53SIVUyFksoJMIaY7HLoKWIb7wxhrV/a9qEzvd/XIXaWQXBZ9YmJV/fSW4Pa3a34n8Uy1vLJmdTrjEDxBQ2cF4TFmy+w3dSc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
