travis:
  secure:
    BINSTAR_TOKEN: yy4IpJLvRw0CzdJkgtmoCjw7vAYj5axqSsY2vL8tZYJ2InZenHXQFOFYmv+5UtGmiFkjVDc+rd1aUFK/5FwRmy/dL2bPfLLvCCqxSEstNc8BdewUWxAnWdH3NuwYcSQd20eJBs7785W+W9QBtb4KO/1LNpa81NqFhuw3kbYH132gl4xx73U/NoRMa6wn0Deaqz933kair0o55cqSB6oGa62T0Ax9PSF1A332kk9McX4EqX2nucDPWXBO17wwY1Zn0l3xJMCnNkvcxgTXGfJnDBY/0F45BKdE7h6T9zMMMQc3R0D3QATEkMa0eHJ8vJXmpIwJVIUOrYmzrCD1F2KV799pjdDHh9CJ0UNZPmku6JWwvDyEjeSa44QZp31J+a9F0wId5V3KGDQpILzvGRFlaWsyycXwjjYrr5jUo0ns/oesKBBP6z+vELN/Fq8AZHUM9CT9Gt3DbLX8+JkR9uIvvseWxokWCyPSZLE/MywPfXCJoH7aujYrcOK2BwGvsPblQbVPox1mIpH6T66HQBogl9VICGNu8hVhOfKEHE1oEjZAzkQfKKOLm4R8PIHzTINwIMKr5mIQhS7xOV0Pv0GEl0xy7hH0lYuICjvavOgeK3imYy+tfrbvQdXUYJ0dhYyt2IfBu0gEGhGnwHZOnLmerdb/s4UE90N1evF9/m+/WGA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
